### ISSUE TITLE
Cuando se busca una materia con nombre muy largo algunos elementos del interfaz pierden su posición original

### ISSUE THREAD

**Issue by xyos** [siajs/prometeo#1]
por ejempo  MOVILIDAD, SOSTENIBILIDAD, MEDIOAMBIENTE Y TERRITORIO: NUEVOS CONCEPTOS PARA OBTENER CALID...

**Comment by gioacostax** [comment]
Por ahora se reduce a 86 caracteres permitidos en la caja antes de añadir puntos...
