### ISSUE TITLE
Una materia borra a la otra al elegirla

### ISSUE THREAD

**Issue by gucoloradoc** [siajs/prometeo#3]
El grupo 2 de introducción a la ciencia e ingeniería de materiales se cruza con el grupo 1 de finanzas y finanzas borra al de materiales. 
Sede Bogotá y no seleccioné ningún plan de estudios.

Éxitos, y excelente herramienta.

**Comment by gioacostax** [comment]
@zurjak88 ¿Que código son las materias "introducción a la ciencia e ingeniería de materiales" y "Finanzas"?

**Comment by gucoloradoc** [comment]
@gioacostax El código de Intro. a la ciencia de materiales es 1000040 y Finanzas 2016741

**Comment by gioacostax** [comment]
@zurjak88 No veo el fallo especifico con el ejemplo que me propone, pero me hizo darme cuenta de un bug grave... Tome en cuenta que en la lista que se muestra, si usted selecciona un grupo que se cruza con otro grupo que **no ha sido seleccionado**, este se desaparece ya que se cruza.

**Comment by gioacostax** [comment]
Fixed - [b7ae2f6](https://github.com/siajs/prometeo/commit/b7ae2f607314dbebf3462e02f5aa7f8f69af899e)
